[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lobs = "GDjye2re8UKJFaDf6ez45vjSyqWvBLffeRNTfgi3fpfL"

[programs.devnet]
lobs = "GDjye2re8UKJFaDf6ez45vjSyqWvBLffeRNTfgi3fpfL"

[programs.mainnet]
lobs = "GDjye2re8UKJFaDf6ez45vjSyqWvBLffeRNTfgi3fpfL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
